version: '3'
services:
  node:
    build: ./app
    env_file:
      - ./.env
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - "${MYSQL_HOST}"
  db:
    build: ./db
    ports:
      - "3306:3306"
    env_file:
      - ./.env
volumes:
  data-volume: